### ISSUE TITLE
I can't init a Chromecast with a complex friendly name

### ISSUE THREAD

**Issue by kylekinnaman** [diequeiroz/start-chromecast-CLI#4]
I'm trying to start multiple Chromecasts on OSX to run Greenscreen, using cron and startcast. I'm not able to start any of them with startcast at the command line because the friendly name includes spaces and a hyphen. 

e.g. startcast "Company - Lounge" [APP_ID]
yields this error: Invalid action: Company - Lounge

I've tried escaping the name (Company\ -\ Lounge), wrapping in both single and double quotes, and nothing seems to work.

**Comment by diequeiroz** [comment]
Run:

startcast start "Company - Lounge" [APP_ID]

Tell me if it works for you

**Comment by kylekinnaman** [comment]
Sorry for not commenting sooner - I just got back to fixing this.

Adding the _start_ method works for me.
